### PR TITLE
#274 Synopsys HW CRC insertion fix

### PR DESCRIPTION
**Pull request by PhilippFinke1988**
This pull request fixes the HW CRC insertion issue with the Synopsys Ethernet MAC.

### CODE REVIEW

**Comment by PhilippFinke1988** [comment]
What's the status on this pull request?

**Comment by mateusz-holenko** [comment]
Hi @PhilippFinke1988, thanks for this contribution!

I was planning to add some automatic tests for this, but I guess this shouldn't block the fix from merging.
Please take a look at: https://github.com/renode/renode-infrastructure/commit/fad7d99f1d0d20b2de61cf53128f07e97ae92111 - it removes the packet recreation completely. 

Could you verify if this solution works for you (you can use the master branch as the commit is already there)?

**Comment by PhilippFinke1988** [comment]
@mateusz-holenko Your change seems to work, but as you mentioned adding automatic tests for this sounds like a good idea. I would prefer your changes over mine, so you can reject and close this pull request.

**Comment by mateusz-holenko** [comment]
Good to hear that this version works fine for you.

We'll add an automatic test in the future, but since the fix is upstreamed I'll close this PR now.

**Pull request closed without merging**
